config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  get 'search', to: 'pages#search', as: :search

  resources :cocktails do
    resources :doses, only: [:new, :create]
  end

  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
 

  def self.generate_unsplash_photo
    "https://source.unsplash.com/collection/2284026/1600x1200?#{rand(10000000000)}"
  end
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :cocktail, uniqueness: { scope: :ingredient }
  validates :description, presence: true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  def index
    @cocktail_options = Ingredient.all.map { |c| [c.name, c.id]}
    if params[:query].present?
      @cocktails = Cocktail.joins(:ingredients).where(ingredients: { id: params[:query] })
    else
      @cocktails = Cocktail.all
    end
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
  end

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def create
  end

  def destroy
    @dose = Dose.find(params[:id])
    if @dose.destroy
      redirect_to cocktail_path(@dose.cocktail)
    end
  end

  private

  def Dose_Params
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/cocktails/_banner.html.erb
<div class="banner position-relative" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= @cocktail.remote_photo_url %>')">
  
</div>

app/views/cocktails/_cocktail_card.html.erb
<div class='d-flex card col-xs-12 col-sm-6 col-md-4 col-lg-3 px-0 my-4 mx-4'>
  <%= link_to cocktail_path(cocktail_card.id) do %><img class="card-img-top" src=<%=cocktail_card.thumbnail %> alt=<%= cocktail_card.name %>><% end %>
  <div class="card-body p-1">
    <%= link_to cocktail_path(cocktail_card.id) do %><h5 class="card-title my-2" style="text-align: center;"><%= cocktail_card.name %></h5><% end %>
  </div>
</div>

app/views/cocktails/index.html.erb
  <div id="main-banner">
  <div class="container d-flex justify-content-center flex-column h-100">
  <div>
    <h1 class="my-3 headline">Try our award-winning cocktail recipes.</h1></div>
    <div class='form-group'>
        <%= form_tag cocktails_path, method: :get, id: 'search-form' do %>
          <p class='mr-4 headline-2'>I've got</p><%= select_tag :query, options_from_collection_for_select(Ingredient.all.order(name: :asc), :id, :name), class: 'form-control custom-select', style: 'height: 3rem; max-width: 500px; background-color: white;' %>
          <%= submit_tag "Let's get shaking", class: 'btn btn-primary search-btn' %>
        <% end %>
      </div>
  </div>
  </div>

  <div class='container mt-2 py-2 bg-white'>
  <div class="row"><h1 class='mt-4'>All our cocktails</h1>
</div>
    <div class='row d-flex'>
      <% unless @cocktails.empty? %>
        <%= render partial: 'cocktail_card', collection: @cocktails %>
      <% else %>
        <h2>There are no cocktails with that ingredient yet. </h2>
      <% end %>
    </div>
  </div>

<script>

  $(document).on('ready', function () {
    $("#query").select2({
      placeholder: "Choose an ingredient",
      theme: "bootstrap4"
    });

    if(performance.navigation.type == 2){
   location.reload(true);
}
  });

</script>

app/views/cocktails/new.html.erb
<div class="container">Hi</div>

app/views/cocktails/show.html.erb
<%= render 'banner'  %>
<div class='container'>
  <div class='row d-flex justify-content-left mt-5'>
    <div class='col-sm-2'>
    <%= link_to cocktails_path do %><h3 class="fas fa-long-arrow-alt-left"></h3><% end %>
    </div>
  </div>
  <div class='row d-flex justify-content-center border'>
    <div class='col-sm-4'>
      <img src=<%= @cocktail.thumbnail %> style="width: 300px;">
    </div>
    <div class='col-sm-4 bg-white mx-5'>
    <h4>Ingredients</h4>
      <ul style="list-style-type: none; padding: 0;">
      <% @cocktail.doses.each do |dose| %>
        <li><%= dose.ingredient.name %> - <%= dose.description %><%= link_to '[x]', dose_path(dose), method: :delete %></li>
      <% end %>
      </ul>
      <h4>Instructions</h4>
      <p style=><%= @cocktail.instructions %></p>
    </div>
      <div class='col-sm-3 bg-white'>
        <h4>Add an Ingredient</h4>
      </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

   <meta name="viewport" content="width=device-width, initial-scale=1">
   <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Last Minute Cocktails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="/path/to/select2.css">
    <link rel="stylesheet" href="/path/to/select2-bootstrap4.css">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
      <%= javascript_pack_tag "rails" %>
      <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>

app/views/pages/home.html.erb
  <div id="main-banner">
  <div class="container d-flex justify-content-center flex-column h-100">
  <div>
    <h1 class="my-3 headline">Try our award-winning cocktail recipes.</h1>
  </div>
   <%= simple_form_for :home_search, wrapper: :inline_form, html: { id: 'search-form', class: 'form-inline my-5', data: { controller: 'pages' } }, url: search_path, method: :get do |f| %>
      <%= f.input :keyword, label: false, class: 'form-control-lg' %>
      <%= f.button :submit, "I'm thirsty", class: 'btn-primary', id: 'search-button' %>
    <% end %>
      </div>
  </div>
  </div>

app/views/pages/search.html.erb
This is the searhc page

app/views/shared/_navbar.html.erb
  <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-transparent">
  <a class="navbar-brand" href="#">LastMinuteCocktails</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      
    </ul>
    <form class="form-inline mr-2">
    <button class="btn btn-outline-light mr-3" type="button">Browse</button>
    <button class="btn btn-outline-success" type="button">Add a Cocktail</button>
    
  </form>
  </div>
  
</nav>